"""creacion de comment y fregrance tablas

Revision ID: e3d6fcb9c5bd
Revises: 80a8046ac846
Create Date: 2021-07-14 15:14:09.553244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d6fcb9c5bd'
down_revision = '80a8046ac846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragrance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fragrance_code', sa.Integer(), nullable=True),
    sa.Column('essential_club', sa.Boolean(), nullable=True),
    sa.Column('vigente', sa.Boolean(), nullable=True),
    sa.Column('application', sa.String(length=100), nullable=True),
    sa.Column('commercial_name', sa.String(length=100), nullable=True),
    sa.Column('box', sa.Integer(), nullable=True),
    sa.Column('cost_kilo_us', sa.Float(), nullable=True),
    sa.Column('selling_price_aud', sa.Float(), nullable=True),
    sa.Column('first_family', sa.String(length=100), nullable=True),
    sa.Column('second_family', sa.String(length=100), nullable=True),
    sa.Column('third_family', sa.String(length=100), nullable=True),
    sa.Column('market_type', sa.String(length=100), nullable=True),
    sa.Column('nota_salida', sa.String(length=100), nullable=True),
    sa.Column('nota_cuerpo', sa.String(length=100), nullable=True),
    sa.Column('nota_fondo', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('sample_size', sa.Float(), nullable=True),
    sa.Column('technology', sa.String(length=100), nullable=True),
    sa.Column('collection_prom', sa.String(length=100), nullable=True),
    sa.Column('shortlisted', sa.Boolean(), nullable=True),
    sa.Column('won_selling', sa.Boolean(), nullable=True),
    sa.Column('natural_extracts', sa.String(length=100), nullable=True),
    sa.Column('allergen', sa.Float(), nullable=True),
    sa.Column('natural_percentage', sa.Boolean(), nullable=True),
    sa.Column('natural_derived', sa.Boolean(), nullable=True),
    sa.Column('ecocert', sa.Boolean(), nullable=True),
    sa.Column('bio_degradable', sa.Boolean(), nullable=True),
    sa.Column('dangerous_good', sa.Boolean(), nullable=True),
    sa.Column('ai', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fragrance_code')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fragrance_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fragrance_id'], ['fragrance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_table('comment')
    op.drop_table('fragrance')
    # ### end Alembic commands ###
